version: '3.7'

services:

  postgis_db:
    image: postgis/postgis
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Welcome1!
      POSTGRES_DB: streuobstportal
      POSTGRES_USER: root
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
      - "5432:5432"
