version: '3.7'

services:

  postgis_db:
    image: postgis/postgis
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Welcome1!
      POSTGRES_DB: streuobstportal
      POSTGRES_USER: root
